# Generated by Django 3.2.5 on 2021-07-03 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Van',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('wheelbase', models.DecimalField(decimal_places=2, max_digits=15)),
                ('price_low', models.DecimalField(decimal_places=2, max_digits=15)),
                ('price_high', models.DecimalField(decimal_places=2, max_digits=15)),
                ('max_weight', models.DecimalField(decimal_places=2, max_digits=15)),
                ('engine', models.CharField(max_length=30)),
                ('drive', models.CharField(max_length=30)),
                ('width', models.DecimalField(decimal_places=2, max_digits=15)),
                ('height', models.DecimalField(decimal_places=2, max_digits=15)),
                ('passengers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Suspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='components.category')),
            ],
        ),
        migrations.CreateModel(
            name='RoofRack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='components.category')),
            ],
        ),
        migrations.CreateModel(
            name='Paint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='components.category')),
            ],
        ),
        migrations.CreateModel(
            name='HeadLights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='components.category')),
            ],
        ),
        migrations.CreateModel(
            name='Framing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=30)),
                ('dimensions', models.CharField(max_length=30)),
                ('unit_measure', models.CharField(max_length=30)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('weight_per_unit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='components.category')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='components.category')),
            ],
        ),
    ]
