# Generated by Django 3.2.5 on 2021-07-03 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_heatinsulation_soundinsulation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wiring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=30, null=True)),
                ('brand', models.CharField(blank=True, max_length=30, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=30, null=True)),
                ('unit_measure', models.CharField(blank=True, max_length=30, null=True)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('weight_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='components.category')),
            ],
        ),
        migrations.CreateModel(
            name='WireInsulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=30, null=True)),
                ('brand', models.CharField(blank=True, max_length=30, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=30, null=True)),
                ('unit_measure', models.CharField(blank=True, max_length=30, null=True)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('weight_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='components.category')),
            ],
        ),
        migrations.CreateModel(
            name='TwelveVolt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=30, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=30, null=True)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('weight_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='components.category')),
            ],
        ),
        migrations.CreateModel(
            name='SystemMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=30, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=30, null=True)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('weight_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='components.category')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_type', models.CharField(blank=True, max_length=30, null=True)),
                ('brand', models.CharField(blank=True, max_length=30, null=True)),
                ('storage_capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=30, null=True)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('weight_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='components.category')),
            ],
        ),
        migrations.CreateModel(
            name='Shore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=30, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=30, null=True)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('weight_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='components.category')),
            ],
        ),
        migrations.CreateModel(
            name='Inverter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=30, null=True)),
                ('model', models.CharField(blank=True, max_length=30, null=True)),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
                ('wattage', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('surge', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('efficiency', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=30, null=True)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('weight_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='components.category')),
            ],
        ),
        migrations.CreateModel(
            name='BusBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensions', models.CharField(blank=True, max_length=30, null=True)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('weight_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='components.category')),
            ],
        ),
        migrations.CreateModel(
            name='Breaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=30, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=30, null=True)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('weight_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='components.category')),
            ],
        ),
    ]
