# Generated by Django 3.2.5 on 2021-07-03 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_breaker_busbar_inverter_shore_storage_systemmonitor_twelvevolt_wireinsulation_wiring'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemmonitor',
            name='brand',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='SolarPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=30, null=True)),
                ('wattage', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('power_per_cell', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('num_cells', models.IntegerField(blank=True, null=True)),
                ('efficiency', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=30, null=True)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('weight_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('walkable', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='components.category')),
            ],
        ),
        migrations.CreateModel(
            name='Heater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=30, null=True)),
                ('power_usage', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=30, null=True)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('weight_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='components.category')),
            ],
        ),
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=30, null=True)),
                ('power_usage', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=30, null=True)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('weight_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='components.category')),
            ],
        ),
        migrations.CreateModel(
            name='ChargeController',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=30, null=True)),
                ('volts', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('amps', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=30, null=True)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('weight_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='components.category')),
            ],
        ),
        migrations.CreateModel(
            name='AC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=30, null=True)),
                ('power_usage', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=30, null=True)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('weight_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='components.category')),
            ],
        ),
    ]
