# Generated by Django 3.2.5 on 2021-07-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0007_auto_20210705_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='van',
            name='van_type',
            field=models.CharField(default='Cargo', max_length=30),
            preserve_default=False,
        ),
    ]
