# Generated by Django 3.2.5 on 2021-07-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0008_van_van_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='van',
            name='van_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
