# Generated by Django 3.2.5 on 2021-07-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0009_alter_van_van_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='van',
            name='height',
        ),
        migrations.RemoveField(
            model_name='van',
            name='price_high',
        ),
        migrations.RemoveField(
            model_name='van',
            name='price_low',
        ),
        migrations.RemoveField(
            model_name='van',
            name='width',
        ),
        migrations.AddField(
            model_name='van',
            name='external_height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='van',
            name='external_length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='van',
            name='external_width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='van',
            name='internal_height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='van',
            name='internal_length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='van',
            name='internal_width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='van',
            name='price_new',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='van',
            name='price_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='van',
            name='transmission',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
