# Generated by Django 3.2.5 on 2021-07-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0010_auto_20210705_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='van',
            old_name='internal_height',
            new_name='cargo_height',
        ),
        migrations.RenameField(
            model_name='van',
            old_name='internal_length',
            new_name='cargo_length',
        ),
        migrations.RenameField(
            model_name='van',
            old_name='internal_width',
            new_name='cargo_width',
        ),
        migrations.AddField(
            model_name='van',
            name='fuel_capacity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='van',
            name='mpg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
