# Generated by Django 3.2.5 on 2021-07-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0011_auto_20210705_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='van',
            name='year',
            field=models.CharField(default=2021, max_length=30),
            preserve_default=False,
        ),
    ]
