# Generated by Django 3.2.5 on 2021-07-12 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0013_auto_20210711_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='heatinsulation',
            name='item',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='roofrack',
            name='item',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='soundinsulation',
            name='item',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
