# Generated by Django 3.0.14 on 2021-08-29 16:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0015_auto_20210809_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='van',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
