# Generated by Django 3.0.14 on 2021-08-31 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0016_van_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExteriorPaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=30, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('unit_measure', models.CharField(blank=True, max_length=30, null=True)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('weight_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='components.Category')),
            ],
        ),
        migrations.RenameModel(
            old_name='Paint',
            new_name='InteriorPaint',
        ),
        migrations.DeleteModel(
            name='Wall',
        ),
    ]
